<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e7805d2a-75f4-44c1-9f8b-7cefdc7402c5</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_positive_growth</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[1]/header[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#post-1722 .entry-title a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>