<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c79e0a0d-d3f2-49b9-8ff3-ebb475ddf165</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_bo_tu_duong_toc_va_co_the_tu_okame_t</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[6]/header[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#post-1505 .entry-title a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>