<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dd7c5898-c01a-4d41-93e8-c62f8b77b859</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_top_thuong_hieu_my_pham_organic_tot_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[4]/header[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#post-1555 [href='http\:\/\/172\.31\.23\.56\/2021\/10\/top-5-thuong-hieu-my-pham-organic-tot-nhat-the-gioi\/']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>