<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9f29ff28-6b3f-4638-b56a-de2398914c80</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_an_tho_danh_cho_lua_tuoi_nao</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[1]/header[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='http\:\/\/172\.31\.23\.56\/2021\/10\/an-tho-danh-cho-lua-tuoi-nao\/']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>