<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>274002a9-ad47-40fc-95ea-190dea1dff46</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_comment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/form[1]/p[2]/textarea[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'comment')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>comment</value>
        <webElementGuid>2a64107a-8cc3-463a-90ef-3ea480c99f78</webElementGuid>
    </webElementProperties>
</WebElementEntity>